### ISSUE TITLE
Mpath syntax

### ISSUE THREAD

**Issue by KurtDeGreeff** [Badgerati/Monocle#1]
Hi, Thanks for your cool module.
I'm struggling with **ClickElement** for clicking the right element in a table.
Could you show the Mpath equivalent for Xpath /html/body/table/tbody/tr[2]/td[2] ?

If you know better ways to do this..this is my html element..much appreciated:
<td class="menu" onmouseover="this.className = 'menu_hover';" onmouseout="this.className = 'menu';" onclick="parent.location.href = 'frames.lhtml?target=user_settings';">
<img alt="Setup the system." src="/images/start/user_settings.gif">System Setup<br>
<span class="description">Setup the system.</span></td>

**Comment by KurtDeGreeff** [comment]
Now in code block ;-)
`<td class="menu" onmouseover="this.className = 'menu_hover';" onmouseout="this.className = 'menu';" onclick="parent.location.href = 'frames.lhtml?target=user_settings';">
<img alt="Setup the system." src="/images/start/user_settings.gif">System Setup<br>
<span class="description">Setup the system.</span></td>`

**Comment by Badgerati** [comment]
Hey, 

I'll have to write up some quick docs for mpath when I get chance. Not at my computer at the moment but off the top of my head the equivalent should be: 

table[0]/tbody/tr[2]/td[2]

Assuming you have more the one table on your page :)

**Comment by KurtDeGreeff** [comment]
Thx a lot, but yeah I only have one table on the page.. ;)
Gives me following error
	Clicking element: **table[0]/tbody/tr[2]/td[2]**
Monocle session: Totem, Failed
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\monocle\Monocle.psm1:82 char:59
+             $foundControls = $controls | ForEach-Object { $_.getElementsByTagNam ...
+                                                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Also when I use slightly other syntax **table/tbody/tr[2]/td[2]**, same error..
Meanwhile I think I already tried every possible way..but no hero today.
Do you know how to solve? Many thanks

**Comment by Badgerati** [comment]
Hmm, if I try a mock HTML table locally it works out. Would you be able to send me the HTML of the page you're trying to use, or just a mock of the HTML with the table?

**Comment by KurtDeGreeff** [comment]
Here you go..thx in advance
`<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Workspace</title>
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<link href="/css/basic.css" rel="stylesheet" type="text/css" />
<link href="/css/start.css" rel="stylesheet" type="text/css" />
</head>

<body>

<table cellspacing="0">
<tbody>
<tr>
<th colspan="2" class="top">Workspace</th>
<td class="top_right"></td>
</tr>
<tr>
<td rowspan="1" class="left"></td>
<td class="menu" onclick="parent.location.href = 'frames.lhtml?target=user_settings';" onmouseover="this.className = 'menu_hover';" onmouseout="this.className = 'menu';">
<img src="/images/start/user_settings.gif" alt="Setup the system." />System Setup<br />
<span class="description">Setup the system.</span></td>
<td rowspan="10" class="bottom_right"></td>
</tr>
<tr>
<td colspan="2" class="bottom"></td>
</tr>
</tbody>
</table>

<p><B>MAC:&nbsp;</B>00:15:3e:00:e0:91
<BR><B>Firmware:&nbsp;</B>55.01s SE
<p>
</body>
</html>`

**Comment by KurtDeGreeff** [comment]
`<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Intro 8 Workspace</title>
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<link href="/css/basic.css" rel="stylesheet" type="text/css" />
<link href="/css/start.css" rel="stylesheet" type="text/css" />
</head>

<body>

<table cellspacing="0">
<tbody>
<tr>
<th colspan="2" class="top">Intro 8 Workspace</th>
<td class="top_right"></td>
</tr>
<tr>
<td rowspan="1" class="left"></td>
<td class="menu" onclick="parent.location.href = 'frames.lhtml?target=user_settings';" onmouseover="this.className = 'menu_hover';" onmouseout="this.className = 'menu';">
<img src="/images/start/user_settings.gif" alt="Setup the system." />System Setup<br />
<span class="description">Setup the system.</span></td>
<td rowspan="10" class="bottom_right"></td>
</tr>
<tr>
<td colspan="2" class="bottom"></td>
</tr>
</tbody>
</table>

<p><B>MAC:&nbsp;</B>00:15:3e:00:e0:91
<BR><B>Firmware:&nbsp;</B>55.01s SE  (build 124.17)
3.0.17-qmatic-2
<p>
</body>
</html>`

**Comment by Badgerati** [comment]
Thanks, think I may have found it. MPath is zero-indexed, so it was finding the wrong <tr> tag. If you try the following it should work:

```
table/tbody/tr[1]/td[1]
```

**Comment by KurtDeGreeff** [comment]
Just tried your suggestion but this gives an exception:
`Clicking element: table/tbody/tr[1]/td[1]
Monocle session: Totem, Failed


Uitzondering van HRESULT: 0x800A138A
At C:\Program Files\WindowsPowerShell\Modules\monocle\Functions\InMonocleSession.ps1:57 char:9
+         throw $_.Exception
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : Uitzondering van HRESULT: 0x800A138A`

**Comment by Badgerati** [comment]
I've had a look around and it would appear that the error is thrown due to a JavaScript error on the page:

* https://social.technet.microsoft.com/Forums/scriptcenter/en-US/33be53ea-3afe-49e7-b586-41de95593373/exception-from-hresult-0x800a138a-at-line?forum=winserverpowershell
* http://stackoverflow.com/questions/28118469/0x800a138a-javascript-runtime-error-function-expected
* http://stackoverflow.com/questions/33376664/0x800a138a-javascript-runtime-error-function-expected-in-ajax-call

Is there by change an error in some JS on your page?

There's also been some mentions of this error cropping up on Intranets, and a possible registry value might be required:

* http://stackoverflow.com/questions/18117322/powershell-web-page-automation-works-on-internet-not-intranet

Running the `ClickElement` on my machine for the HTML supplied, it works; so there's a possibility it's could be one of the above.

Failing that, what OS/IE and PS versions are you running?
