### ISSUE TITLE
Test-MonocleElement returns True when an Id does not exist

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Monocle#19]
Steps to reproduce
1. Have an HTML page, don't have an element with an id of 'test'
1. Have a monocle script do `Test-MonocleElement -Id "test"`

Expected Result
* Returns False

Actual Result
* Return True

**Comment by Fraham** [comment]
Created pull request #20 to fix this issue

**Comment by Badgerati** [comment]
Merged.
